-- It's fun
-- Created by T1ger

if (SERVER) then
    AddCSLuaFile('weapons/client/graffiti-ui-settings.lua')
elseif (CLIENT) then
    include('weapons/client/graffiti-ui-settings.lua')
end
function SWEP:GraffitiUI()
    if (CLIENT) then

        net.Start('GraffitiUIOpenCnanger')
            net.WriteString('1')
        net.SendToServer()

        local Frame = vgui.Create('DFrame')
            Frame:SetSize(900, 450)
            Frame:SetPos(ScrW() / 2 - 450, ScrH() / 2 - 250)
            Frame:SetTitle('Graffiti Сustomizer')
            Frame:SetVisible(true)
            Frame:SetDraggable(true)
            Frame:ShowCloseButton(true)
            Frame:SetPaintShadow(true)
            Frame:MakePopup()

            Frame.Paint = function(self, w, h)
                draw.RoundedBox(8, 0, 0, w, h, Color(0, 0, 0, 200))
            end

            Frame.OnClose = function()
                net.Start('GraffitiUIOpenCnanger')
                    net.WriteString('0')
                net.SendToServer()
            end
----------------------
            local DLabel = vgui.Create('DLabel', Frame)
                DLabel:SetPos(20, 45)
                DLabel:SetFont('HDRDemoText')
                DLabel:SetColor(Color(255, 255, 255, 255))
                DLabel:SetText('Colors')

            local DColor = vgui.Create('DLabel', Frame)
                DColor:SetPos(15, 397)
                DColor:SetSize(180, 25)
                DColor:SetColor(Color(255, 255, 255, 255))
                if (LocalPlayer():GetNWBool('GraffitiBrush') == true) then
                    DColor:SetText('Brush: ')
                else
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                end
            local DSize = vgui.Create('DLabel', Frame)
                DSize:SetPos(95, 400)
                DSize:SetColor(Color(255, 255, 255, 255))
                if (LocalPlayer():GetNWBool('GraffitiBrush') == true) then
                    DSize:SetText('')
                else
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                end
            local DBrush = vgui.Create('DLabel', Frame)
                DBrush:SetPos(50, 400)
                DBrush:SetColor(Color(255, 255, 255, 255))
                if (LocalPlayer():GetNWBool('GraffitiBrush') == true) then
                    DBrush:SetText(LocalPlayer():GetNWString('GraffitiColor'))
                else
                    DBrush:SetText('')
                end

            local BackgroundImage = vgui.Create('DImage', Frame)
                BackgroundImage:SetPos(830, 50)
                BackgroundImage:SetImage('materials/images/graffiti-ui.png')
                BackgroundImage:SetSize(256, 256)
----------------------
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(25, 80)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(0, 68, 46, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Fir')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Fir')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(65, 80)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(23, 171, 137, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Emerald')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Emerald')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(105, 80)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(77, 170, 71, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Mint')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Mint')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(145, 80)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(35, 100, 176, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Ocean')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Ocean')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(185, 80)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(83, 148, 204, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Sky')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Sky')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(225, 80)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(188, 204, 233, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Linen')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Linen')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(25, 120)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(255, 207, 58, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Corn')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Corn')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(65, 120)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(247, 215, 141, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Gold')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Gold')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(105, 120)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(252, 223, 45, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Lemon')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Lemon')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(145, 120)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(217, 224, 31, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Barberry')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Barberry')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(185, 120)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(255, 237, 179, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Biscuit')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Biscuit')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(225, 120)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(218, 181, 154, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Skin')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Skin')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(25, 160)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(222, 90, 55, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Coral')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Coral')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(65, 160)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(241, 89, 83, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Assol')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Assol')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(105, 160)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(246, 146, 35, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Orange')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Orange')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(145, 160)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(203, 157, 200, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Lavender')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Lavender')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(185, 160)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(145, 121, 183, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Lilac')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Lilac')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(225, 160)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(144, 59, 126, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Plum')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Plum')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(25, 200)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(0, 0, 0, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Black')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Black')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(65, 200)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(90, 90, 92, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Graphite')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Graphite')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(105, 200)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(103, 104, 106, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Shadow')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Shadow')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(145, 200)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(147, 149, 157, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Asphalt')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Asphalt')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(185, 200)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(241, 241, 242, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Silver')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Silver')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(225, 200)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(255, 255, 255, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'White')
                    LocalPlayer():SetNWBool('GraffitiBrush', false)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('White')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(false)
                    net.SendToServer()
                    DColor:SetText('Color: ' .. LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    DBrush:SetText('')
                end
----------------------
            local DLabel = vgui.Create('DLabel', Frame)
                DLabel:SetPos(600, 45)
                DLabel:SetFont('HDRDemoText')
                DLabel:SetColor(Color(255, 255, 255, 255))
                DLabel:SetText('Brush')
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(610, 80)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(111, 111, 111, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'EmoTexture')
                    LocalPlayer():SetNWBool('GraffitiBrush', true)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('EmoTexture')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(true)
                    net.SendToServer()
                    DColor:SetText('Brush: ')
                    DBrush:SetText(LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(650, 80)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(111, 111, 111, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Amogus')
                    LocalPlayer():SetNWBool('GraffitiBrush', true)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Amogus')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(true)
                    net.SendToServer()
                    DColor:SetText('Brush: ')
                    DBrush:SetText(LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(690, 80)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(111, 111, 111, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Floppa')
                    LocalPlayer():SetNWBool('GraffitiBrush', true)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Floppa')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(true)
                    net.SendToServer()
                    DColor:SetText('Brush: ')
                    DBrush:SetText(LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('')
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(730, 80)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(111, 111, 111, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiColor', 'Shrek')
                    LocalPlayer():SetNWBool('GraffitiBrush', true)
                    net.Start('GraffitiColorChanger')
                        net.WriteString('Shrek')
                    net.SendToServer()
                    net.Start('GraffitiBrushChanger')
                        net.WriteBool(true)
                    net.SendToServer()
                    DColor:SetText('Brush: ')
                    DBrush:SetText(LocalPlayer():GetNWString('GraffitiColor'))
                    DSize:SetText('')
                end
----------------------
            local DLabel = vgui.Create('DLabel', Frame)
                DLabel:SetPos(600, 130)
                DLabel:SetFont('HDRDemoText')
                DLabel:SetColor(Color(255, 255, 255, 255))
                DLabel:SetText('Size')
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(610, 165)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(140, 140, 140, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiSize', 'Small')
                    net.Start('GraffitiSizeChanger')
                        net.WriteString('Small')
                    net.SendToServer()
                    if (LocalPlayer():GetNWBool('GraffitiBrush') == true) then
                        DSize:SetText('')
                    else
                        DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    end
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(650, 165)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(140, 140, 140, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiSize', 'Normal')
                    net.Start('GraffitiSizeChanger')
                        net.WriteString('Normal')
                    net.SendToServer()
                    if (LocalPlayer():GetNWBool('GraffitiBrush') == true) then
                        DSize:SetText('')
                    else
                        DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    end
                end
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(690, 165)
                DermaButton:SetSize(35, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(140, 140, 140, 255))
                    end
                DermaButton.DoClick = function()
                    LocalPlayer():SetNWString('GraffitiSize', 'Large')
                    net.Start('GraffitiSizeChanger')
                        net.WriteString('Large')
                    net.SendToServer()
                    if (LocalPlayer():GetNWBool('GraffitiBrush') == true) then
                        DSize:SetText('')
                    else
                        DSize:SetText('Size: ' .. LocalPlayer():GetNWString('GraffitiSize'))
                    end
                end
----------------------
            local DLabel = vgui.Create('DLabel', Frame)
                DLabel:SetPos(600, 210)
                DLabel:SetSize(200, 25)
                DLabel:SetFont('HDRDemoText')
                DLabel:SetColor(Color(255, 255, 255, 255))
                DLabel:SetText('Next Spraying')
            local DNumSlider = vgui.Create('DNumSlider', Frame)
                DNumSlider:SetPos(440, 240)
                DNumSlider:SetSize(400, 25)
                DNumSlider:SetText('')
                DNumSlider:SetMin(0)
                DNumSlider:SetMax(1)
                DNumSlider:SetValue(LocalPlayer():GetNWInt('GraffitiSpraying'))
            DNumSlider.OnValueChanged = function(panel, value)
                if (value != LocalPlayer():GetNWInt('GraffitiSpraying')) then
                    LocalPlayer():SetNWInt('GraffitiSpraying', value)
                    net.Start('GraffitiSprayingChanger')
                        net.WriteString(tonumber(value))
                    net.SendToServer()
                end
            end
            local DNumSlider = vgui.Create('DNumSlider', Frame)
                DNumSlider:SetPos(440, 280)
                DNumSlider:SetSize(400, 25)
                DNumSlider:SetText('')
                DNumSlider:SetMin(0)
                DNumSlider:SetMax(1)
                DNumSlider:SetValue(LocalPlayer():GetNWInt('GraffitiSlider'))
            local time = 0
            DNumSlider.OnValueChanged = function(panel, value)
                if (value != LocalPlayer():GetNWInt('GraffitiSlider')) then
                    if (value != 1) then
                        LocalPlayer():SetNWInt('GraffitiSlider', value)
                    elseif (value == 1) and (LocalPlayer():GetNWInt('GraffitiSettings') == 1) then
                        DNumSlider:SetValue(value - 0.1)
                    elseif (value == 1) and (CurTime() > time) and (LocalPlayer():GetNWInt('GraffitiSettings') == 0) and (LocalPlayer():IsValid()) then
                        time = CurTime() + 1
                        LocalPlayer():SetNWInt('GraffitiSettings', 1)
                        if (LocalPlayer():IsSuperAdmin() == true) then
                            RunConsoleCommand('graffiti_max_distance', 140)
                        end
                        GraffitiSettings()
                    end
                end
            end
            local DLabel = vgui.Create('DLabel', Frame)
                DLabel:SetPos(648, 295)
                DLabel:SetSize(200, 25)
                DLabel:SetColor(Color(255, 255, 255, 255))
                DLabel:SetText('NumSlider (open settings)')
----------------------
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(630, 350)
                DermaButton:SetSize(200, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(205, 205, 205, 255))
                    end
                DermaButton.DoClick = function()
                    if (LocalPlayer():IsAdmin()) and (LocalPlayer():IsValid()) then
                        RunConsoleCommand('graffiti_clear')
                        if (LocalPlayer():GetNWBool('GraffitiInterfaceSounds') == true) then
                            LocalPlayer():EmitSound('derma/gclear.mp3', 100, math.random(90, 120), 1, CHAN_AUTO)
                        end
                    end
                end
            local DLabel = vgui.Create('DLabel', Frame)
                DLabel:SetPos(670, 355)
                DLabel:SetSize(200, 25)
                DLabel:SetColor(Color(110, 110, 110, 255))
                DLabel:SetText('Graffiti Clear (Admins Only)')
            local DermaButton = vgui.Create('DButton', Frame)
                DermaButton:SetText('')
                DermaButton:SetPos(630, 395)
                DermaButton:SetSize(200, 35)
                DermaButton.Paint = function(self, w, h)
                        draw.RoundedBox(5, 0, 0, w, h, Color(205, 205, 205, 255))
                    end
                DermaButton.DoClick = function()
                    local ply = LocalPlayer()
                    file.Write('graffiti-swep/graffiti-settings.txt', ply:GetNWString('GraffitiColor') .. '\n' .. ply:GetNWString('GraffitiSize') .. '\n' .. tostring(ply:GetNWBool('GraffitiBrush')) .. '\n' .. ply:GetNWInt('GraffitiSpraying') .. '\n' .. ply:GetNWInt('GraffitiSlider'))
                    if (LocalPlayer():GetNWBool('GraffitiInterfaceSounds') == true) then
                        ply:EmitSound('derma/gsaved.mp3', 100, math.random(90, 120), 1, CHAN_AUTO)
                    end
                end
            local DLabel = vgui.Create('DLabel', Frame)
                DLabel:SetPos(680, 400)
                DLabel:SetSize(200, 25)
                DLabel:SetColor(Color(110, 110, 110, 255))
                DLabel:SetText('Save Your Settings')
----------------------
            local DLabel = vgui.Create('DLabel', Frame)
                DLabel:SetPos(10, 425)
                DLabel:SetSize(100, 25)
                DLabel:SetColor(Color(120, 120, 120, 255))
                DLabel:SetText('Created by T1ger')
                DLabel:SetMouseInputEnabled(true)
            DLabel.DoDoubleClick = function()
                net.Start('SecretChanger')
                net.SendToServer()
                if (LocalPlayer():GetNWBool('GraffitiInterfaceSounds') == true) then
                    LocalPlayer():EmitSound('derma/gsecret.mp3', 100, math.random(90, 120), 1, CHAN_AUTO)
                end
            end
    end
end